"""
BACKOFFICE USERS
"""
USERS = "api/backoffice/user/"
USER_INFO = "api/backoffice/user/%s/"
SEARCH_BACKOFFICE_USERS = "api/backoffice/user/?search=%s"
BACKOFFICE_CONFIRM_EMAIL = "api/backoffice/user/%s/toggle_email_confirmation/"
BACKOFFICE_VERIFY_USER_ACCOUNT = "api/backoffice/user/%s/verify/"
USER_ACCOUNTS = "api/backoffice/user/%s/account_prefetch/"
BACKOFFICE_EDIT_PERSONAL_INFO = "api/backoffice/user/%s/edit_info/"
USERS_BONUSES = "api/backoffice/user/%s/bonuses/records/?page=1&page_size=10&tab=bonuses"
